{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pass-gen.fullname" . }}
  labels:
    {{- include "pass-gen.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pass-gen.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: External
      external:
        metricName: {{ .Values.autoscaling.cpuMetricName }}
        target:
          type: Utilization
          averageValue: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}%
    - type: External
      external:
        metricName: {{ .Values.autoscaling.memoryMetricName }}
        target:
          type: Utilization
          averageValue: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}%
{{- end }}
