# metrics-server.yaml

{{- if .Values.metricsServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  replicas: {{ .Values.metricsServer.replicaCount }}
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: {{ .Values.metricsServer.image.repository }}:{{ .Values.metricsServer.image.tag }}
        imagePullPolicy: {{ .Values.metricsServer.image.pullPolicy }}
        resources: {{ toYaml .Values.metricsServer.resources | nindent 12 }}
      {{- if .Values.metricsServer.certificatesDir }}
      volumeMounts:
        - name: certs-volume
          mountPath: {{ .Values.metricsServer.certificatesDir }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
spec:
  selector:
    app: metrics-server
  ports:
    - name: http
      port: 443
      targetPort: 443
{{- end }}
